config/routes.rb
Fast::Application.routes.draw do
  devise_for :users
  resources :users
  resources :tasks do
    member do
      get 'apply'
      get 'cancel'
      get 'finish'
    end
  end
  
  root to: "users#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    can :create, User
    if user.present?
      if user.admin
        can :manage, :all
      else
        can :read, :all
        can :manage, User, id: user.id
        can [:create, :cancel, :edit, :update], Task, consumer_id: user.id
        can :cancel, Task, doer_id: user.id
        can :apply, Task, doer_id: nil
        cannot :apply, Task, consumer_id: user.id
        can [:confirm, :destroy], Task, consumer_id: user.id
      end
    end
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :consumer_id, :description, :doer_id, :title, :state
  belongs_to :consumer, :foreign_key => "consumer_id", :class_name => "User"
  belongs_to :doer, :foreign_key => "doer_id", :class_name => "User"
  
  scope :undone, where(doer_id: nil)
  scope :done, where('doer_id IS NOT NULL')
  
  validates :consumer_id, presence: true
  validates :title, presence: true
  
  state_machine :state, :initial => :ready do

    event :cancel do
      transition :in_process => :ready
    end

    event :apply do
      transition :ready => :in_process
    end

    event :finish do
      transition :in_process => :done
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :admin, :city, :name
  
  validates :name, presence: true

  has_many :offers, :class_name => "Task", :foreign_key => "consumer_id"
  has_many :tasks, :class_name => "Task", :foreign_key => "doer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource

  def index
    @tasks = Task.where('doer_id IS NULL AND consumer_id != ?', current_user.id)
  end

  def create
    @task.consumer_id = current_user.id
    if @task.save
      redirect_to root_path, notice: 'Task was successfully created.' 
    else
      render :new
    end
  end

  def update
    if @task.update_attributes(params[:task])
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def finish
    @task.finish!
    redirect_to root_path
  end
  
  def apply
    @task.apply!
    @task.doer_id = current_user.id
    @task.save
    redirect_to root_path
  end

  def cancel
    @task.doer_id = nil
    @task.save
    @task.cancel!
    redirect_to root_path
  end

  def destroy
    @task.destroy
    redirect_to root_path
  end

  def show
  end
  def new
  end
  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    if user_signed_in?
      @user = User.find(current_user.id)
    end
  end
  
  def create
    if @user.save
      redirect_to @user, notice: 'User was successfully created.' 
    else
      render :new
    end
  end

  def update
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.' 
    else
      render :edit
    end
  end

  def destroy 
    @user.destroy
    redirect_to root_path, notice: 'User was successfully destroyed.' 
  end

  def show
    @offers = Task.where('doer_id IS NULL AND consumer_id = ?', @user.id)
  end
  def new
  end
  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Fast
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    =render partial: "shared/menu"
    - if flash[:alert]
      %p#alert= flash[:alert]
    - if flash[:notice]
      %p#notice= notice
    = yield

app/views/shared/_menu.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %ul.nav
        -if current_user
          .span3
            %li.span1
              =link_to root_path do
                %p.text-info
                  =current_user.name
            %li= link_to 'Create a task', new_task_path
            %li= link_to 'Find a task', tasks_path 
            
        .span2.pull-right
          %li= link_to 'Sign up', new_user_path 
          -if current_user.nil? 
            %li= link_to 'Sign in', new_user_session_path
          -else
            %li= link_to 'Sign out', destroy_user_session_path, method: :delete
        

app/views/shared/_tasks.html.haml
- if tasks.empty?
  Nothing here yet...
- tasks.each do |task| 
  = task.title
  = task.state
  -unless task.doer.nil?
    = link_to task.doer.name, user_path(task.doer.id)
    applied for
    \#{link_to task.title, task_path(task.id)}
  - if can? :cancel, task
    \#{link_to 'Cancel', cancel_task_path(task.id)}
  - if can? :apply, task
    \#{link_to 'Apply', apply_task_path(task.id)}
  - if can? :finish, task
    \#{link_to 'Finish', finish_task_path(task.id)}
  - if can? :destroy, task
    \#{link_to 'Delete', task_path(task.id), method: :delete}

app/views/tasks/_form.html.haml
= form_for(@task) do |f|
  - if @task.errors.any?
    #error_explanation
      %h2
        = pluralize(@task.errors.count, "error")
        prohibited this task from being saved:
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit

app/views/tasks/edit.html.haml
%h1 Editing task
= render 'form'
= link_to 'Show', @task
|
\#{link_to 'Back', tasks_path}

app/views/tasks/index.html.haml
-if current_user
  %h1 All available tasks
  - @tasks.each do |task|
    = task.title
    = "Created at: #{task.created_at}"
    = link_to 'Do this task', apply_task_path(task.id)
  .row
    = link_to 'New Task', new_task_path
    = link_to 'Home page', root_path

app/views/tasks/new.html.haml
%h1 New task
= render 'form'
= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p
  Title:
  = @task.title
%p
  Description:
  = @task.description
%p
  Consumer:
  = @task.consumer.name
- unless @task.doer.nil?
  %p
    Doer:
    = @task.doer.name
= link_to 'Edit', edit_task_path(@task)
|
\#{link_to 'Back', tasks_path}

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions
    = f.submit
  .field
    = f.label :admin
    = f.check_box :admin

app/views/users/_users.html.haml
%h3 Listing users
.row
  .span1 Admin
  .span2 Name
  .span2 City
- users.each do |user|
  .row#index[user]
    .span1= user.admin
    .span2= user.name
    .span2= user.city
    .span1= link_to 'Show', user
    .span1= link_to 'Edit', edit_user_path(user)
    .span1= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

app/views/users/edit.html.haml
%h1 Editing user
= render 'form'
= link_to 'Show', @user
|
\#{link_to 'Back', users_path}

app/views/users/index.html.haml
- if current_user
  %h3.new_line My tasks
  .my_offers=render partial: 'shared/tasks', locals:{tasks:@user.offers}
  %h3.new_line I must do
  =render partial: 'shared/tasks', locals:{tasks:@user.tasks}
  %h3.new_line They applied for my tasks
  =render partial: 'shared/tasks', locals:{tasks:@user.offers.done}
- if can? :manage, :all
  =render partial: 'users', locals:{ users: @users }

app/views/users/new.html.haml
%h1 New user
= render 'form'
= link_to 'Back', users_path

app/views/users/show.html.haml
%p User info
%p
  %b Name:
  = @user.name
%p
  %b City:
  = @user.city
%h4.new_line="#{@user.name}'s tasks"
.my_offers=render partial: 'shared/tasks', locals:{tasks:@offers}
=#{link_to 'Back', users_path}